Added rebranding email for all users
uCV-team/ucv pull request #390
Opened 2022-03-14 13:16 UTC by ritik-bluebash

issue #386 
Added rebranding email for all users with CTA link
![Screenshot from 2022-03-14 18-44-47](https://user-images.githubusercontent.com/80153678/158179203-7b764b53-4059-4a56-929c-9f1ffbaff559.png)

2022-03-15 10:20 UTC, vishal-bluebash commented on lib/tasks/email_rebranding.rake
> +    User.all.each do |user|
We should filter it users over here

2022-03-15 10:21 UTC, vishal-bluebash commented on app/mailers/user_mailer.rb
> +    attachments.inline['new_logo.svg'] = File.read(Rails.root.join(*%w[app javascript images new_logo.svg]))
User who is not confirmed yet will also be confirmed when they click on magic link

2022-03-15 10:21 UTC, vishal-bluebash requested changes
clarification  and update needed

2022-03-15 10:22 UTC, vishal-bluebash commented
@ValerioVillani please check screenshot and verify content

2022-03-15 10:24 UTC, ValerioVillani commented
> @ValerioVillani please check screenshot and verify content

Hi @vishal-bluebash I edited the message together with Duccio, you can find the new one here: 

https://github.com/uCV-team/ucv/issues/386

2022-03-15 10:25 UTC, ritik-bluebash commented on app/mailers/user_mailer.rb
> +    attachments.inline['new_logo.svg'] = File.read(Rails.root.join(*%w[app javascript images new_logo.svg]))
Yes sir. The user account gets confirmed, published and the user gets signed in as well to their new uCV account.

2022-03-15 11:44 UTC, vishal-bluebash approved these changes

2022-03-21 14:31 UTC, ValerioVillani approved these changes

2022-03-22 05:02 UTC, merged